name: create-release

permissions:
  id-token: write
  contents: write
  packages: write
  actions: read

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GHCR_PASSWORD }} | docker login -u ${{ secrets.GHCR_USERNAME }} --password-stdin ghcr.io

      - name: Release with GoReleaser
        uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-release-goreleaser.yml@0.37.2
        with:
          go-version: 1.21.4
          version: ${{ github.event.inputs.version }}
          docker-platforms: linux/amd64,linux/arm64
          docker-tags: |
            ghcr.io/witt-wcc-ops/sbom-operator:${{ github.event.inputs.version }}
            ghcr.io/witt-wcc-ops/sbom-operator:latest
          cosign-repository: ghcr.io/WITT-WCC-OPS/sbom-operator-metadata
        secrets:
          token: ${{ secrets.GHCR_TOKEN }}
          pat: ${{ secrets.REPO_ACCESS }}
          ghcr-password: ${{ secrets.GHCR_PASSWORD }}

  job-image-vcn:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GHCR_PASSWORD }} | docker login -u ${{ secrets.GHCR_USERNAME }} --password-stdin ghcr.io

      - name: Job Image for VCN
        uses: ckotzbauer/sbom-operator/.github/workflows/release-job-image.yml@main
        with:
          version: ${{ github.event.inputs.version }}
          job-image: vcn
          docker-platforms: linux/amd64
          docker-tags: |
            ghcr.io/witt-wcc-ops/sbom-operator/vcn:${{ github.event.inputs.version }}
            ghcr.io/witt-wcc-ops/sbom-operator/vcn:latest
          cosign-repository: ghcr.io/WITT-WCC-OPS/sbom-operator-metadata
        secrets:
          token: ${{ secrets.GHCR_TOKEN }}
          pat: ${{ secrets.REPO_ACCESS }}
          ghcr-password: ${{ secrets.GHCR_PASSWORD }}
